# Generated by Django 3.1.12 on 2025-12-07 15:13

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20251207_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('POST', 'Post'), ('COMMENT', 'Comment')], max_length=10)),
                ('media_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], default='TEXT', max_length=10)),
                ('media_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted'), ('FLAGGED', 'Flagged')], default='ACTIVE', max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS_ONLY', 'Friends Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='user.user')),
                ('parent_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content.content')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.content',),
        ),
    ]
