# Generated by Django 3.1.12 on 2025-12-07 15:21

import bson.objectid
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20251207_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
    ]
