# Generated by Django 3.1.12 on 2025-12-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_make_content_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
